# Generated by Django 4.2.2 on 2023-06-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_status', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagpessoa', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='filesupload'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=25, unique=True, verbose_name='Telefone')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('status', models.BooleanField(default=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.acao', verbose_name='Próximos Passos')),
                ('categoria_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status', verbose_name='Status da Pessoa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.origem', verbose_name='Origem do Lead')),
                ('tag', models.ManyToManyField(to='crm.tagpessoa', verbose_name='Tag')),
                ('temperatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.temperatura', verbose_name='Temperatura')),
            ],
        ),
    ]
