# Generated by Django 4.2.2 on 2023-06-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_acao_empresa_origem_status_tagpessoa_temperatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='origem',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='tagpessoa',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='temperatura',
            old_name='status',
            new_name='ativo',
        ),
    ]
